import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    int counterfields = 0;

    public Home() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    String NAME, SRCODE, LAST, MIDDLE;

    Home(String last, String str, String middle, String SR) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage();

        this.NAME = str;
        USERNAME.setText(NAME);
        this.SRCODE = SR;
        this.LAST = last;
        this.MIDDLE = middle;

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        LocalDateTime now = LocalDateTime.now();

        timeClock.setText(String.valueOf(dtf.format(now)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        uniformBtn = new javax.swing.JButton();
        USERNAME = new javax.swing.JLabel();
        booksBtn = new javax.swing.JButton();
        tabHolder = new javax.swing.JPanel();
        homeTab = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        contactsTab = new javax.swing.JPanel();
        contactsLabel = new javax.swing.JLabel();
        faqsTab = new javax.swing.JPanel();
        faqsLabel = new javax.swing.JLabel();
        devTab = new javax.swing.JPanel();
        devLabel = new javax.swing.JLabel();
        timeClock = new javax.swing.JLabel();
        shopHeader = new javax.swing.JLabel();
        shopBody = new javax.swing.JLabel();
        panelHolder = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        aboutTitle = new javax.swing.JLabel();
        about1 = new javax.swing.JLabel();
        about2 = new javax.swing.JLabel();
        about3 = new javax.swing.JLabel();
        aboutCopyright = new javax.swing.JLabel();
        contactsPanel = new javax.swing.JPanel();
        contactsTitle = new javax.swing.JLabel();
        contactsLandline = new javax.swing.JLabel();
        contactsEmail = new javax.swing.JLabel();
        contactsFacebookPage = new javax.swing.JLabel();
        contactsCopyright = new javax.swing.JLabel();
        aboutCopyright1 = new javax.swing.JLabel();
        faqsPanel = new javax.swing.JPanel();
        faqsTitle = new javax.swing.JLabel();
        faqsCopyright = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        answer1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        answer2a = new javax.swing.JLabel();
        answer2b = new javax.swing.JLabel();
        aboutCopyright2 = new javax.swing.JLabel();
        devPanel = new javax.swing.JPanel();
        caponponImage = new javax.swing.JLabel();
        caponpon1 = new javax.swing.JLabel();
        caponpon2 = new javax.swing.JLabel();
        dagliImage = new javax.swing.JLabel();
        dagli1 = new javax.swing.JLabel();
        dagli2 = new javax.swing.JLabel();
        garingImage = new javax.swing.JLabel();
        garing1 = new javax.swing.JLabel();
        garing2 = new javax.swing.JLabel();
        ordonezImage = new javax.swing.JLabel();
        ordonez1 = new javax.swing.JLabel();
        ordonez2 = new javax.swing.JLabel();
        cruzImage = new javax.swing.JLabel();
        cruz2 = new javax.swing.JLabel();
        cruz1 = new javax.swing.JLabel();
        dev1 = new javax.swing.JLabel();
        dev2 = new javax.swing.JLabel();
        devCopyright = new javax.swing.JLabel();
        aboutCopyright3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(968, 727));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }

            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hi,");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 40));

        logoutBtn.setBackground(new java.awt.Color(204, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, 30));

        uniformBtn.setBackground(new java.awt.Color(204, 0, 0));
        uniformBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        uniformBtn.setForeground(new java.awt.Color(255, 255, 255));
        uniformBtn.setText("UNIFORM");
        uniformBtn.setBorder(null);
        uniformBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniformBtnActionPerformed(evt);
            }
        });
        getContentPane().add(uniformBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 440, 53));

        USERNAME.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        USERNAME.setForeground(new java.awt.Color(0, 0, 0));
        USERNAME.setText("[FIRST NAME]");
        getContentPane().add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 40));

        booksBtn.setBackground(new java.awt.Color(204, 0, 0));
        booksBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        booksBtn.setForeground(new java.awt.Color(255, 255, 255));
        booksBtn.setText("BOOKS");
        booksBtn.setBorder(null);
        booksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksBtnActionPerformed(evt);
            }
        });
        getContentPane().add(booksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 440, 51));

        tabHolder.setBackground(new java.awt.Color(0, 0, 0));

        homeTab.setBackground(new java.awt.Color(0, 0, 0));
        homeTab.setPreferredSize(new java.awt.Dimension(171, 43));
        homeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeTabMouseClicked(evt);
            }
        });

        homeLabel.setBackground(new java.awt.Color(0, 0, 0));
        homeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("HOME");
        homeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
                homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addContainerGap()));
        homeTabLayout.setVerticalGroup(
                homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homeLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        contactsTab.setBackground(new java.awt.Color(204, 0, 0));
        contactsTab.setPreferredSize(new java.awt.Dimension(171, 43));
        contactsTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsTabMouseClicked(evt);
            }
        });

        contactsLabel.setBackground(new java.awt.Color(0, 0, 0));
        contactsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        contactsLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactsLabel.setText("CONTACTS");
        contactsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout contactsTabLayout = new javax.swing.GroupLayout(contactsTab);
        contactsTab.setLayout(contactsTabLayout);
        contactsTabLayout.setHorizontalGroup(
                contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contactsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(contactsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addContainerGap()));
        contactsTabLayout.setVerticalGroup(
                contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contactsLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        faqsTab.setBackground(new java.awt.Color(204, 0, 0));
        faqsTab.setPreferredSize(new java.awt.Dimension(171, 43));
        faqsTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faqsTabMouseClicked(evt);
            }
        });

        faqsLabel.setBackground(new java.awt.Color(0, 0, 0));
        faqsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        faqsLabel.setForeground(new java.awt.Color(255, 255, 255));
        faqsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        faqsLabel.setText("FAQs");
        faqsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout faqsTabLayout = new javax.swing.GroupLayout(faqsTab);
        faqsTab.setLayout(faqsTabLayout);
        faqsTabLayout.setHorizontalGroup(
                faqsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(faqsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(faqsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addContainerGap()));
        faqsTabLayout.setVerticalGroup(
                faqsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(faqsLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        devTab.setBackground(new java.awt.Color(204, 0, 0));
        devTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devTabMouseClicked(evt);
            }
        });

        devLabel.setBackground(new java.awt.Color(0, 0, 0));
        devLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        devLabel.setForeground(new java.awt.Color(255, 255, 255));
        devLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devLabel.setText("DEVELOPERS");
        devLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout devTabLayout = new javax.swing.GroupLayout(devTab);
        devTab.setLayout(devTabLayout);
        devTabLayout.setHorizontalGroup(
                devTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(devTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(devLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addContainerGap()));
        devTabLayout.setVerticalGroup(
                devTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(devLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        javax.swing.GroupLayout tabHolderLayout = new javax.swing.GroupLayout(tabHolder);
        tabHolder.setLayout(tabHolderLayout);
        tabHolderLayout.setHorizontalGroup(
                tabHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabHolderLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(homeTab, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98,
                                        Short.MAX_VALUE)
                                .addComponent(contactsTab, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(faqsTab, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(devTab, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)));
        tabHolderLayout.setVerticalGroup(
                tabHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homeTab, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(contactsTab, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(devTab, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(faqsTab, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        getContentPane().add(tabHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 203, 1070, 40));

        timeClock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timeClock.setForeground(new java.awt.Color(255, 255, 255));
        timeClock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeClock.setText("HR:MIN");
        getContentPane().add(timeClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 220, 30));

        shopHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeHeader_a.png"))); // NOI18N
        getContentPane().add(shopHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 250));

        shopBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeBody.png"))); // NOI18N
        getContentPane().add(shopBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 260));

        panelHolder.setBackground(new java.awt.Color(0, 0, 0));

        homePanel.setBackground(new java.awt.Color(0, 0, 0));
        homePanel.setPreferredSize(new java.awt.Dimension(1070, 244));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutTitle.setText("ABOUT ");
        homePanel.add(aboutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 330, 52));

        about1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about1.setForeground(new java.awt.Color(255, 255, 255));
        about1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about1.setText("University Shop provides convenience for students/parents of Batangas State University. ");
        homePanel.add(about1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 750, 30));

        about2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about2.setForeground(new java.awt.Color(255, 255, 255));
        about2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about2.setText(
                "Available books and school uniforms are provided through the application for easier access that makes");
        homePanel.add(about2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 870, 30));

        about3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about3.setForeground(new java.awt.Color(255, 255, 255));
        about3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about3.setText(" it time efficient for the students/parents and the Resource Generation Office.");
        homePanel.add(about3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 740, 30));

        aboutCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutCopyright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeCopyright.png"))); // NOI18N
        homePanel.add(aboutCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        contactsPanel.setBackground(new java.awt.Color(0, 0, 0));
        contactsPanel.setPreferredSize(new java.awt.Dimension(1070, 244));
        contactsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactsTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        contactsTitle.setForeground(new java.awt.Color(255, 255, 255));
        contactsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactsTitle.setText("CONTACTS");
        contactsPanel.add(contactsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 281, 52));

        contactsLandline.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        contactsLandline.setForeground(new java.awt.Color(255, 255, 255));
        contactsLandline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactsLandline.setText("Landline: 980-0385/980-0387/980-0394 loc 1221 / 1130");
        contactsPanel.add(contactsLandline, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 720, -1));

        contactsEmail.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        contactsEmail.setForeground(new java.awt.Color(255, 255, 255));
        contactsEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactsEmail.setText("Email Address: rgo.main@g.batastate-u.edu.ph, resourcegenerationoffice@gmail.com");
        contactsPanel.add(contactsEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 720, -1));

        contactsFacebookPage.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        contactsFacebookPage.setForeground(new java.awt.Color(255, 255, 255));
        contactsFacebookPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactsFacebookPage.setText("Facebook Page: Batangas State University Resource Generation Office");
        contactsPanel.add(contactsFacebookPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 720, -1));
        contactsPanel.add(contactsCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        aboutCopyright1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutCopyright1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeCopyright.png"))); // NOI18N
        contactsPanel.add(aboutCopyright1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        faqsPanel.setBackground(new java.awt.Color(0, 0, 0));
        faqsPanel.setPreferredSize(new java.awt.Dimension(1070, 244));
        faqsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faqsTitle.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        faqsTitle.setForeground(new java.awt.Color(255, 255, 255));
        faqsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        faqsTitle.setText("Frequently Asked Questions (FAQs)");
        faqsPanel.add(faqsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 620, 52));
        faqsPanel.add(faqsCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        question1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        question1.setForeground(new java.awt.Color(255, 255, 255));
        question1.setText("What if the school uniform/books is out of stock?");
        faqsPanel.add(question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        answer1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        answer1.setForeground(new java.awt.Color(255, 255, 255));
        answer1.setText(
                "Please patiently wait for it to be available again through this application and regularly check for updates.");
        faqsPanel.add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        question2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        question2.setForeground(new java.awt.Color(255, 255, 255));
        question2.setText("Where can I claim the items I ordered?");
        faqsPanel.add(question2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        answer2a.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        answer2a.setForeground(new java.awt.Color(255, 255, 255));
        answer2a.setText(
                "Kindly proceed to  Income Generation Office (IGP) or Resource Generation Office (RGO) with your printed receipt and payment");
        faqsPanel.add(answer2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        answer2b.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        answer2b.setForeground(new java.awt.Color(255, 255, 255));
        answer2b.setText("to claim your oders.");
        faqsPanel.add(answer2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        aboutCopyright2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutCopyright2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeCopyright.png"))); // NOI18N
        faqsPanel.add(aboutCopyright2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        devPanel.setBackground(new java.awt.Color(0, 0, 0));
        devPanel.setPreferredSize(new java.awt.Dimension(1070, 244));
        devPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caponponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/developers/CAPONPON, AERON A.png"))); // NOI18N
        devPanel.add(caponponImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        caponpon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caponpon1.setForeground(new java.awt.Color(255, 255, 255));
        caponpon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caponpon1.setText("CAPONPON,");
        devPanel.add(caponpon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 138, -1));

        caponpon2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        caponpon2.setForeground(new java.awt.Color(255, 255, 255));
        caponpon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caponpon2.setText("AERON A.");
        devPanel.add(caponpon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 138, -1));

        dagliImage
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/developers/DAGLI, MARIANNE NICOLE A.png"))); // NOI18N
        devPanel.add(dagliImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        dagli1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dagli1.setForeground(new java.awt.Color(255, 255, 255));
        dagli1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dagli1.setText("DAGLI,");
        devPanel.add(dagli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 138, -1));

        dagli2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        dagli2.setForeground(new java.awt.Color(255, 255, 255));
        dagli2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dagli2.setText("MARIANNE NICOLE A.");
        devPanel.add(dagli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 150, -1));

        garingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/developers/GARING, LEANDRO M.png"))); // NOI18N
        devPanel.add(garingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        garing1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        garing1.setForeground(new java.awt.Color(255, 255, 255));
        garing1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        garing1.setText("GARING,");
        devPanel.add(garing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 138, -1));

        garing2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        garing2.setForeground(new java.awt.Color(255, 255, 255));
        garing2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        garing2.setText("LEANDRO M.");
        devPanel.add(garing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 100, -1));

        ordonezImage
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/developers/ORDONEZ, MONICA PAULA G.png"))); // NOI18N
        devPanel.add(ordonezImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        ordonez1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ordonez1.setForeground(new java.awt.Color(255, 255, 255));
        ordonez1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordonez1.setText("ORDOÑEZ,");
        devPanel.add(ordonez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 138, -1));

        ordonez2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ordonez2.setForeground(new java.awt.Color(255, 255, 255));
        ordonez2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordonez2.setText("MONICA PAULA G.");
        devPanel.add(ordonez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 130, -1));

        cruzImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/developers/CRUZ, RENZ JULLIANA R.png"))); // NOI18N
        devPanel.add(cruzImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        cruz2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cruz2.setForeground(new java.awt.Color(255, 255, 255));
        cruz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruz2.setText("RENZ JULLIANA R.");
        devPanel.add(cruz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 170, -1));

        cruz1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cruz1.setForeground(new java.awt.Color(255, 255, 255));
        cruz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cruz1.setText("CRUZ,");
        devPanel.add(cruz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 138, -1));

        dev1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dev1.setForeground(new java.awt.Color(255, 255, 255));
        dev1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dev1.setText("THE");
        devPanel.add(dev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        dev2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dev2.setForeground(new java.awt.Color(255, 255, 255));
        dev2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dev2.setText("DEVELOPERS");
        devPanel.add(dev2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        devPanel.add(devCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        aboutCopyright3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutCopyright3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeImages/homeCopyright.png"))); // NOI18N
        devPanel.add(aboutCopyright3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        javax.swing.GroupLayout panelHolderLayout = new javax.swing.GroupLayout(panelHolder);
        panelHolder.setLayout(panelHolderLayout);
        panelHolderLayout.setHorizontalGroup(
                panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homePanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contactsPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(faqsPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(devPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        panelHolderLayout.setVerticalGroup(
                panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contactsPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(faqsPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(panelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(devPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        getContentPane().add(panelHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 471, 1070, 244));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }// GEN-LAST:event_logoutBtnActionPerformed

    private void uniformBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_uniformBtnActionPerformed
        // TODO add your handling code here:
        // new uniform().setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        new uniform(LAST, NAME, MIDDLE, SRCODE).setVisible(true);
        dispose();
    }// GEN-LAST:event_uniformBtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        USERNAME.setText(NAME);
    }// GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }// GEN-LAST:event_formWindowLostFocus

    private void booksBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_booksBtnActionPerformed
        // TODO add your handling code here:
        new Books(LAST, NAME, MIDDLE, SRCODE).setVisible(true);
        dispose();
    }// GEN-LAST:event_booksBtnActionPerformed

    private void homeTabMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_homeTabMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(true);
        contactsPanel.setVisible(false);
        faqsPanel.setVisible(false);
        devPanel.setVisible(false);
        homeTab.setBackground(Color.black);
        contactsTab.setBackground(new Color(204, 0, 0));
        faqsTab.setBackground(new Color(204, 0, 0));
        devTab.setBackground(new Color(204, 0, 0));
    }// GEN-LAST:event_homeTabMouseClicked

    private void contactsTabMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_contactsTabMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        contactsPanel.setVisible(true);
        faqsPanel.setVisible(false);
        devPanel.setVisible(false);
        homeTab.setBackground(new Color(204, 0, 0));
        contactsTab.setBackground(Color.black);
        faqsTab.setBackground(new Color(204, 0, 0));
        devTab.setBackground(new Color(204, 0, 0));
    }// GEN-LAST:event_contactsTabMouseClicked

    private void faqsTabMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_faqsTabMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        contactsPanel.setVisible(false);
        faqsPanel.setVisible(true);
        devPanel.setVisible(false);

        homeTab.setBackground(new Color(204, 0, 0));
        contactsTab.setBackground(new Color(204, 0, 0));
        faqsTab.setBackground(Color.black);
        devTab.setBackground(new Color(204, 0, 0));
    }// GEN-LAST:event_faqsTabMouseClicked

    private void devTabMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_devTabMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        contactsPanel.setVisible(false);
        faqsPanel.setVisible(false);
        devPanel.setVisible(true);

        homeTab.setBackground(new Color(204, 0, 0));
        contactsTab.setBackground(new Color(204, 0, 0));
        faqsTab.setBackground(new Color(204, 0, 0));
        devTab.setBackground(Color.black);
    }// GEN-LAST:event_devTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Steel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        try {
            FlatArcIJTheme.setup();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void setIconImage() { // Setting the icon of the program
        URL iconUrl = this.getClass().getResource("images/univ_shop_icon.png");
        Toolkit tk = this.getToolkit();
        setIconImage(tk.getImage(iconUrl));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel USERNAME;
    private javax.swing.JLabel about1;
    private javax.swing.JLabel about2;
    private javax.swing.JLabel about3;
    private javax.swing.JLabel aboutCopyright;
    private javax.swing.JLabel aboutCopyright1;
    private javax.swing.JLabel aboutCopyright2;
    private javax.swing.JLabel aboutCopyright3;
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel answer1;
    private javax.swing.JLabel answer2a;
    private javax.swing.JLabel answer2b;
    private javax.swing.JButton booksBtn;
    private javax.swing.JLabel caponpon1;
    private javax.swing.JLabel caponpon2;
    private javax.swing.JLabel caponponImage;
    private javax.swing.JLabel contactsCopyright;
    private javax.swing.JLabel contactsEmail;
    private javax.swing.JLabel contactsFacebookPage;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JLabel contactsLandline;
    private javax.swing.JPanel contactsPanel;
    private javax.swing.JPanel contactsTab;
    private javax.swing.JLabel contactsTitle;
    private javax.swing.JLabel cruz1;
    private javax.swing.JLabel cruz2;
    private javax.swing.JLabel cruzImage;
    private javax.swing.JLabel dagli1;
    private javax.swing.JLabel dagli2;
    private javax.swing.JLabel dagliImage;
    private javax.swing.JLabel dev1;
    private javax.swing.JLabel dev2;
    private javax.swing.JLabel devCopyright;
    private javax.swing.JLabel devLabel;
    private javax.swing.JPanel devPanel;
    private javax.swing.JPanel devTab;
    private javax.swing.JLabel faqsCopyright;
    private javax.swing.JLabel faqsLabel;
    private javax.swing.JPanel faqsPanel;
    private javax.swing.JPanel faqsTab;
    private javax.swing.JLabel faqsTitle;
    private javax.swing.JLabel garing1;
    private javax.swing.JLabel garing2;
    private javax.swing.JLabel garingImage;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel ordonez1;
    private javax.swing.JLabel ordonez2;
    private javax.swing.JLabel ordonezImage;
    private javax.swing.JPanel panelHolder;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel shopBody;
    private javax.swing.JLabel shopHeader;
    private javax.swing.JPanel tabHolder;
    private javax.swing.JLabel timeClock;
    private javax.swing.JButton uniformBtn;
    // End of variables declaration//GEN-END:variables

}
