import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Statement;

public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    int countersrcode = 0;
    int counterpass = 0;
    int counterRegsrcode = 0;
    int counterRegpass = 0;
    int counterRegpassConf = 0;
    int counterRegsur = 0;
    int counterReggiven = 0;
    int counterRegmid = 0;

    public Login() {
        initComponents();
        password.setEchoChar((char) 0);
        setResizable(false);
        setLocationRelativeTo(null);

        setIconImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TABS = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        srcode = new javax.swing.JFormattedTextField();
        showPwordBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        srcodeRegTb = new javax.swing.JFormattedTextField();
        passwordRegTb = new javax.swing.JPasswordField();
        confPasswordRegTb = new javax.swing.JPasswordField();
        lastNameRegTb = new javax.swing.JTextField();
        givenNameRegTb = new javax.swing.JTextField();
        middleNameRegTb = new javax.swing.JTextField();
        signupBtn = new javax.swing.JButton();
        showPwordBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to the University Shop!");
        setFocusTraversalPolicyProvider(true);
        setName("Welcome to the University Shop"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }

            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        TABS.setToolTipText("");
        TABS.setAlignmentX(0.0F);
        TABS.setAlignmentY(0.0F);
        TABS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("Password ");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setFocusCycleRoot(true);
        loginBtn.setNextFocusableComponent(loginBtn);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        srcode.setForeground(new java.awt.Color(153, 153, 153));
        try {
            srcode.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        srcode.setText("12-00000");
        srcode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        srcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srcodeFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                srcodeFocusLost(evt);
            }
        });
        srcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srcodeMouseClicked(evt);
            }
        });

        showPwordBox.setText("Show Password");
        showPwordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwordBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("SR Code");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Password");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head_1_scaled.png"))); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
                loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginPanelLayout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addGroup(loginPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(showPwordBox)
                                                        .addGroup(loginPanelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel8)
                                                                .addComponent(password,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(srcode,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel7))))
                                        .addGroup(loginPanelLayout.createSequentialGroup()
                                                .addGap(183, 183, 183)
                                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGap(0, 81, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(73, 73, 73)));
        loginPanelLayout.setVerticalGroup(
                loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(5, 5, 5)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPwordBox)
                                .addGap(31, 31, 31)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)));

        TABS.addTab("Login", loginPanel);

        srcodeRegTb.setForeground(new java.awt.Color(153, 153, 153));
        try {
            srcodeRegTb.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        srcodeRegTb.setText("1200000");
        srcodeRegTb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srcodeRegTbFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                srcodeRegTbFocusLost(evt);
            }
        });
        srcodeRegTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srcodeRegTbMouseClicked(evt);
            }
        });

        passwordRegTb.setForeground(new java.awt.Color(153, 153, 153));
        passwordRegTb.setText("Password ");
        passwordRegTb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegTbFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegTbFocusLost(evt);
            }
        });
        passwordRegTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordRegTbMouseClicked(evt);
            }
        });

        confPasswordRegTb.setForeground(new java.awt.Color(153, 153, 153));
        confPasswordRegTb.setText("Confirm Password ");
        confPasswordRegTb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confPasswordRegTbFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                confPasswordRegTbFocusLost(evt);
            }
        });
        confPasswordRegTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confPasswordRegTbMouseClicked(evt);
            }
        });

        lastNameRegTb.setForeground(new java.awt.Color(0, 0, 0));

        givenNameRegTb.setForeground(new java.awt.Color(0, 0, 0));
        givenNameRegTb.setText(" ");

        middleNameRegTb.setForeground(new java.awt.Color(0, 0, 0));

        signupBtn.setBackground(new java.awt.Color(0, 0, 0));
        signupBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("SIGN UP");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        showPwordBox1.setText("Show Password");
        showPwordBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwordBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Given Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Middle Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("SR Code");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head_reg.png"))); // NOI18N

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
                signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signupPanelLayout.createSequentialGroup()
                                .addGroup(signupPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(signupPanelLayout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(signupPanelLayout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(signupPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(signupPanelLayout.createSequentialGroup()
                                                                .addGroup(signupPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(passwordRegTb,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                158,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5))
                                                                .addGap(34, 34, 34)
                                                                .addGroup(signupPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(confPasswordRegTb,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                158,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6)))
                                                        .addGroup(signupPanelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(givenNameRegTb,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(signupPanelLayout.createSequentialGroup()
                                                                        .addGroup(signupPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lastNameRegTb,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        158,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel1))
                                                                        .addGap(34, 34, 34)
                                                                        .addGroup(signupPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(middleNameRegTb,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        158,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(signupPanelLayout.createSequentialGroup()
                                                                        .addGap(245, 245, 245)
                                                                        .addComponent(showPwordBox1))
                                                                .addComponent(jLabel4)
                                                                .addComponent(srcodeRegTb,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(77, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(114, 114, 114)));
        signupPanelLayout.setVerticalGroup(
                signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signupPanelLayout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srcodeRegTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(signupPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(signupPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confPasswordRegTb, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordRegTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPwordBox1)
                                .addGap(31, 31, 31)
                                .addGroup(signupPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(signupPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(middleNameRegTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameRegTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(givenNameRegTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)));

        TABS.addTab("Sign Up", signupPanel);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/side_panel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TABS)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TABS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11));

        getAccessibleContext().setAccessibleName("Welcome to the University Shop");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultLoginFormat(Object component, Boolean status) {

        if (component == srcode) {
            if (status == true) { // Default format of the sr code text field
                srcode.setText("12-00000");
                srcode.setForeground(Color.GRAY);

            } else { // When user clicks the sr code text field
                srcode.setText(null);
                srcode.requestFocus();
                srcode.setForeground(Color.BLACK);
            }

        } else if (component == password) {
            if (status == true) { // Degault format of the password text field
                password.setText("Password ");
                password.setEchoChar((char) 0);
                password.setForeground(Color.GRAY);

            } else { // When the user click the password text field
                password.setText(null);
                password.requestFocus();

                password.setEchoChar('•');
                password.setForeground(Color.BLACK);
            }
        }
    }

    public void setDefaultFormat() {
        srcodeRegTb.setText("12-00000");
        passwordRegTb.setText("Password ");
        confPasswordRegTb.setText("Confirm Password ");
        lastNameRegTb.setText("");
        givenNameRegTb.setText("");
        middleNameRegTb.setText("");
        showPwordBox1.setSelected(false);

        srcodeRegTb.setForeground(Color.GRAY);
        passwordRegTb.setForeground(Color.GRAY);
        confPasswordRegTb.setForeground(Color.GRAY);
    }

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        // auto set passwords to *
        password.setEchoChar((char) 0);
        passwordRegTb.setEchoChar((char) 0);
        confPasswordRegTb.setEchoChar((char) 0);
    }// GEN-LAST:event_formWindowGainedFocus

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        // sign up
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university_shop?useSSL=false",
                    "root", "");
            String srCodeReg = srcodeRegTb.getText();
            String passwordReg = String.valueOf(passwordRegTb.getText());
            String confPasswordReg = String.valueOf(confPasswordRegTb.getText());
            String lastNameReg = lastNameRegTb.getText();
            String givenNameReg = givenNameRegTb.getText();
            String middleNameReg = middleNameRegTb.getText();
            // if user did not enter anything
            if (srCodeReg.equals("  -     ") || passwordReg.equals("") || confPasswordReg.equals("")
                    || lastNameReg.equals("") || givenNameReg.equals("") || middleNameReg.equals("")) {
                JOptionPane.showMessageDialog(this, "Do not leave any field blank.");
                setDefaultFormat();

                // if sr code already in system
            } else {
                String check = "SELECT * from logincredentials WHERE srcode = ?";
                final PreparedStatement ps = con.prepareStatement(check);
                ps.setString(1, srCodeReg);
                final ResultSet resultSet = ps.executeQuery();

                if (resultSet.next()) {
                    final int count = resultSet.getInt(1);
                    JOptionPane.showMessageDialog(this, " SR Code already registered.");
                    setDefaultFormat();

                    // if password confirm does not match password
                } else if (!passwordReg.equals(confPasswordReg)) {
                    JOptionPane.showMessageDialog(this, "Password does not match.");
                    showPwordBox1.setSelected(false);

                    // sign up success
                } else {
                    Statement stmt = con.createStatement();
                    String sql = ("INSERT INTO logincredentials VALUES (null, '" + srCodeReg + "', '" + passwordReg
                            + "', '" + lastNameReg + "', '" + givenNameReg + "', '" + middleNameReg + "' )");
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Sign Up successful");
                    setDefaultFormat();
                    TABS.setSelectedIndex(0);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_signupBtnActionPerformed

    private void confPasswordRegTbMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_confPasswordRegTbMouseClicked
        // TODO add your handling code here:
        // set fields to blank if clicked
        if (counterRegpassConf == 0) {
            confPasswordRegTb.setText("");
            counterRegpassConf += 1;
        }
    }// GEN-LAST:event_confPasswordRegTbMouseClicked

    private void passwordRegTbMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_passwordRegTbMouseClicked
        // TODO add your handling code here:
        // set fields to blank if clicked
        if (counterRegpass == 0) {
            passwordRegTb.setText("");
            counterRegpass += 1;
        }
    }// GEN-LAST:event_passwordRegTbMouseClicked

    private void srcodeRegTbMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_srcodeRegTbMouseClicked
        // TODO add your handling code here:
        // set fields to blank if clicked
        if (counterRegsrcode == 0) {
            srcodeRegTb.setText("");
            counterRegsrcode += 1;
        }
    }// GEN-LAST:event_srcodeRegTbMouseClicked

    private void showPwordBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPwordBoxActionPerformed
        // TODO add your handling code here:
        // set password to * if ticked
        if (showPwordBox.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('•');
        }
    }// GEN-LAST:event_showPwordBoxActionPerformed

    private void srcodeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_srcodeMouseClicked
        // TODO add your handling code here:
        // set fields to blank if clicked
        if (countersrcode == 0) {
            srcode.setText("");
            countersrcode += 1;
        }
    }// GEN-LAST:event_srcodeMouseClicked

    private void srcodeFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_srcodeFocusLost
        // TODO add your handling code here:
        if (srcode.getText().equals("  -     ")) {
            setDefaultLoginFormat(srcode, true);
        }
    }// GEN-LAST:event_srcodeFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        // login
        try {
            // creates connection to database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university_shop?useSSL=false",
                    "root", "");

            String srcode1 = srcode.getText();
            String password1 = String.valueOf(password.getText());

            Statement stmt = con.createStatement();
            String sql = "SELECT *from logincredentials where srcode='" + srcode1 + "' and password='" + password1
                    + "'";
            ResultSet rs = stmt.executeQuery(sql);

            Statement userName = con.createStatement();
            String getName = "SELECT * FROM logincredentials WHERE srcode='" + srcode1 + "'";
            ResultSet rsName = userName.executeQuery(getName);

            Statement userID = con.createStatement();
            String getID = "SELECT id FROM logincredentials WHERE srcode='" + srcode1 + "'";
            ResultSet rsID = userID.executeQuery(getID);
            // checking if user entry is in the databse
            if (rs.next()) {
                String SRCODE = rs.getString("srcode");
                if (rsName.next()) {
                    String homeName = rsName.getString("givenname");
                    String lastName = rsName.getString("lastname");
                    String middleName = rsName.getString("middlename");
                    System.out.println(lastName + ", " + homeName + " " + middleName); // for checking purposes
                }
                String homeName = rsName.getString("givenname");
                String lastName = rsName.getString("lastname");
                String middleName = rsName.getString("middlename");
                if (rsID.next()) {
                    if (rsID.getInt("id") == 1) {// if id is 1 then it is the admin
                        dispose();
                        AdminHome admin = new AdminHome();
                        admin.show();

                    } else {// if not then it is a normal user
                        int id_pass = rsID.getInt("id");
                        new Home(lastName, homeName, middleName, SRCODE).setVisible(true);
                        dispose();
                        // new uniform(SRCODE).setVisible(false);
                    }
                }
            } else {// if password or srcode entered is wrong
                JOptionPane.showMessageDialog(this, " Srcode or Password is incorrect.");
                srcode.setText("12-00000");
                password.setText("Password ");
                showPwordBox.setSelected(false);
                srcode.setForeground(Color.GRAY);
                password.setForeground(Color.GRAY);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_loginBtnActionPerformed

    private void srcodeFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_srcodeFocusGained
        // TODO add your handling code here:
        if (srcode.getText().equals("12-00000")) {
            setDefaultLoginFormat(srcode, false);

        }
    }// GEN-LAST:event_srcodeFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if (password.getText().equals("Password ")) {
            setDefaultLoginFormat(password, false);
        }
    }// GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if (password.getText().length() == 0) {
            setDefaultLoginFormat(password, true);
        }
    }// GEN-LAST:event_passwordFocusLost

    private void srcodeRegTbFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_srcodeRegTbFocusGained
        // TODO add your handling code here:
        if (srcodeRegTb.getText().equals("12-00000")) {
            srcodeRegTb.requestFocus();
            srcodeRegTb.setText(null);
            srcodeRegTb.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_srcodeRegTbFocusGained

    private void srcodeRegTbFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_srcodeRegTbFocusLost
        // TODO add your handling code here:
        if (srcodeRegTb.getText().equals("  -     ")) {
            srcodeRegTb.setText("12-00000");
            srcodeRegTb.setForeground(Color.GRAY);
        }
    }// GEN-LAST:event_srcodeRegTbFocusLost

    private void passwordRegTbFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordRegTbFocusGained
        // TODO add your handling code here:
        if (passwordRegTb.getText().equals("Password ")) {
            passwordRegTb.requestFocus();
            passwordRegTb.setText(null);
            passwordRegTb.setEchoChar('•');
            passwordRegTb.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_passwordRegTbFocusGained

    private void passwordRegTbFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordRegTbFocusLost
        // TODO add your handling code here:
        if (passwordRegTb.getText().length() == 0) {
            passwordRegTb.setEchoChar((char) 0);
            passwordRegTb.setText("Password ");
            passwordRegTb.setForeground(Color.GRAY);
        }
    }// GEN-LAST:event_passwordRegTbFocusLost

    private void confPasswordRegTbFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_confPasswordRegTbFocusGained
        // TODO add your handling code here:
        if (confPasswordRegTb.getText().equals("Confirm Password ")) {
            confPasswordRegTb.requestFocus();
            confPasswordRegTb.setText(null);
            confPasswordRegTb.setEchoChar('•');
            confPasswordRegTb.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_confPasswordRegTbFocusGained

    private void confPasswordRegTbFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_confPasswordRegTbFocusLost
        // TODO add your handling code here:
        if (confPasswordRegTb.getText().length() == 0) {
            confPasswordRegTb.setEchoChar((char) 0);
            confPasswordRegTb.setText("Confirm Password");
            confPasswordRegTb.setForeground(Color.GRAY);
        }
    }// GEN-LAST:event_confPasswordRegTbFocusLost

    private void showPwordBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPwordBox1ActionPerformed
        // TODO add your handling code here:
        if (showPwordBox1.isSelected()) {
            passwordRegTb.setEchoChar((char) 0);
            confPasswordRegTb.setEchoChar((char) 0);
        } else {
            passwordRegTb.setEchoChar('•');
            confPasswordRegTb.setEchoChar('•');
        }
    }// GEN-LAST:event_showPwordBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Steel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        try {
            FlatArcIJTheme.setup();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private void setIconImage() { // Setting the icon of the program
        URL iconUrl = this.getClass().getResource("images/univ_shop_icon.png");
        Toolkit tk = this.getToolkit();
        setIconImage(tk.getImage(iconUrl));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TABS;
    private javax.swing.JPasswordField confPasswordRegTb;
    private javax.swing.JTextField givenNameRegTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameRegTb;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField middleNameRegTb;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordRegTb;
    private javax.swing.JCheckBox showPwordBox;
    private javax.swing.JCheckBox showPwordBox1;
    private javax.swing.JButton signupBtn;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JFormattedTextField srcode;
    private javax.swing.JFormattedTextField srcodeRegTb;
    // End of variables declaration//GEN-END:variables
}
