
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class uniform extends javax.swing.JFrame {

    public uniform() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    String SRCODE, NAME, LASTNAME, MIDDLENAME;

    uniform(String lName, String name, String mName, String str) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage();
        
        this.SRCODE = str;
        this.NAME = name;
        this.LASTNAME = lName;
        this.MIDDLENAME = mName;
        
        nameLabel.setText(LASTNAME + ", " + NAME + " " + " | ");
        srOfUser.setText(SRCODE);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        LocalDateTime now = LocalDateTime.now();  
        subheadTime.setText(String.valueOf(dtf.format(now)));
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtreceipt = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        bckBtn = new javax.swing.JButton();
        uniformHeader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtqty = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        uniformPrice = new javax.swing.JTextField();
        uniformText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        subhead = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        srOfUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subheadTime = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buy Uniforms");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Stock", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
            jTable1.getColumnModel().getColumn(2).setMinWidth(30);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(45);
            jTable1.getColumnModel().getColumn(3).setMinWidth(30);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(45);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, -1, 237));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 218, 400, 131));

        txttotal.setEditable(false);
        txttotal.setText(" ");
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 358, 101, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 358, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 358, 100, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Order Again");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 618, 150, -1));

        txtreceipt.setEditable(false);
        txtreceipt.setColumns(20);
        txtreceipt.setRows(5);
        jScrollPane3.setViewportView(txtreceipt);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 428, -1, 220));

        jButton5.setBackground(new java.awt.Color(204, 11, 11));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("PLACE ORDER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 478, -1, 75));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Print Invoice");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 568, 150, 35));

        bckBtn.setText("Back");
        bckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bckBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 40));

        uniformHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head_uniform.png"))); // NOI18N
        getContentPane().add(uniformHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("My Order");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 188, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 214, 16, 380));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Your Receipt");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 398, -1, -1));

        jPanel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(204, 11, 11));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtqty.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtqty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 454, -1, -1));

        uniformPrice.setEditable(false);
        uniformPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        uniformPrice.setText(" ");

        uniformText.setEditable(false);
        uniformText.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        uniformText.setText(" ");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Available Items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uniformText)
                    .addComponent(uniformPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uniformText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uniformPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 454, -1, -1));

        subhead.setBackground(new java.awt.Color(153, 153, 153));

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("LASTNAME, FIRSTNAME | ");

        srOfUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        srOfUser.setForeground(new java.awt.Color(255, 255, 255));
        srOfUser.setText("SR-CODES");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACCOUNT LOGGED IN:");

        subheadTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        subheadTime.setForeground(new java.awt.Color(255, 255, 255));
        subheadTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subheadTime.setText("HR:MINUTE");

        javax.swing.GroupLayout subheadLayout = new javax.swing.GroupLayout(subhead);
        subhead.setLayout(subheadLayout);
        subheadLayout.setHorizontalGroup(
            subheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subheadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subheadTime, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        subheadLayout.setVerticalGroup(
            subheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subheadLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(subheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srOfUser)
                    .addComponent(subheadTime))
                .addContainerGap())
        );

        getContentPane().add(subhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 970, -1));

        footer.setBackground(new java.awt.Color(9, 9, 9));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BATANGAS STATE UNIVERSITY, THE NATIONAL ENGINEERING UNIVERSITY © 2022 ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 694, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // database connection
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university_shop", "root", "");
       
            Statement st = con.createStatement();
            
            String sql = "select * from availability_C_uniform";
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel unifTable = (DefaultTableModel) jTable1.getModel();
            
            while (rs.next()){
                //add data
                String id = String.valueOf(rs.getInt("ID"));
                String prod = rs.getString("Uniform");
                String quan = String.valueOf(rs.getInt("Quantity"));
                String price = String.valueOf(rs.getInt("Price"));
                
                String unifList[] = {id, prod, quan, price};

                
                unifTable.addRow(unifList);
            }
            jButton1.setEnabled(false);
 
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // add
        DefaultTableModel unifTable1 = (DefaultTableModel)jTable1.getModel();
        if (uniformText.getText().equals(" ")||uniformPrice.getText().equals(" ")){
            JOptionPane.showMessageDialog(this, "Fields Empty");
        }else{
            String data[] = {uniformText.getText(), uniformPrice.getText()};
            
            String unif = uniformText.getText();
            String price = uniformPrice.getText();
            
            int qty = Integer.parseInt(txtqty.getValue().toString());
            int price1 = Integer.parseInt(price);
            int tot = (qty * price1);
            
            DefaultTableModel orders = (DefaultTableModel) jTable2.getModel();

            orders.addRow(new Object[]
            {
                unif,
                price,
                qty,
                tot
            });
            int sum = 0;

            for(int a=0; a<jTable2.getRowCount(); a++)
            {
                sum = sum + Integer.parseInt((jTable2.getValueAt(a, 3).toString()));
                
                txttotal.setText(Integer.toString(sum));
                }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void sales()
    {
        int lastid = 0;
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university_shop", "root", "");
            
            String total = txttotal.getText();
            String srcode = srOfUser.getText();
            
            String query = "insert into sales(srcode, Balance, Date)values(?,?,?)";
            pst = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, srcode);
            pst.setString(2, total);
            pst.setString(3, dtf.format(now));
            pst.executeUpdate();
            ResultSet rs = pst.getGeneratedKeys();
                       
            if (rs.next())
            {
                lastid = rs.getInt(1);
            }
            
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            
            String query1 = "insert into admin_sales(srcode, Name, Quantity, Date, Status)values(?,?,?,?,?)";
            
            String usersrcode = srOfUser.getText();
            
            for (int i = 0; i < model.getRowCount(); i++) {
                String prodname = (String) model.getValueAt(i, 0);
                int qty = (int) model.getValueAt(i, 2);
                pst1 = con.prepareStatement(query1, Statement.RETURN_GENERATED_KEYS);
                pst1.setString(1, usersrcode);
                pst1.setString(2, prodname);
                pst1.setInt(3, qty);
                pst1.setString(4, dtf.format(now));
                pst1.setString(5, "false");
                pst1.executeUpdate();
            }
            
        JOptionPane.showMessageDialog(this, "Order has been placed. Please print the invoice as proof of order.");
            
        } catch (SQLException ex) {
            Logger.getLogger(uniform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(uniform.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //table to text field
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
      
        String unifColumn = model.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String quantityColumn = model.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String priceColumn = model.getValueAt(jTable1.getSelectedRow(), 3).toString();
        
        uniformText.setText(unifColumn);
        uniformPrice.setText(priceColumn);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //remove
        DefaultTableModel orders = (DefaultTableModel) jTable2.getModel();
        
        if (jTable2.getSelectedRowCount() != 0) {
            orders.removeRow(jTable2.getSelectedRow());
            int sum = 0;
            for (int a = 0; a < jTable2.getRowCount(); a++) {
                sum = sum + Integer.parseInt(jTable2.getValueAt(a, 3).toString());
            }
            txttotal.setText(Integer.toString(sum));
        }else{
            if (jTable2.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty");
            } else {
                JOptionPane.showMessageDialog(this, "Select a Row");
            }   
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Clear button
        DefaultTableModel orders = (DefaultTableModel) jTable2.getModel();
        orders.setRowCount(0);
        txtreceipt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //order
        if (jTable2.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Empty orders");
        }else{
            sales();
            receipt();
        }

    }//GEN-LAST:event_jButton5ActionPerformed
public void DateTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        System.out.println(dtf.format(now));
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //print
        try {
            txtreceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(uniform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Home(LASTNAME, NAME, MIDDLENAME, SRCODE).setVisible(true);
    }//GEN-LAST:event_bckBtnActionPerformed
public void receipt(){
        String total = txttotal.getText();
        
        DefaultTableModel orders = new DefaultTableModel();
        orders = (DefaultTableModel) jTable2.getModel();
        
        txtreceipt.setText(txtreceipt.getText() + "**************************************************************\n");
        txtreceipt.setText(txtreceipt.getText() + "                            Batangas State University                  \n");
        txtreceipt.setText(txtreceipt.getText() + "                         Rizal Ave, Extension, Batangas               \n");
        txtreceipt.setText(txtreceipt.getText() + "                                 University Shop                      \n");
        txtreceipt.setText(txtreceipt.getText() + "**************************************************************\n");
        
        //HEADING
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        txtreceipt.setText(txtreceipt.getText() + "Date and Time of order:   " + dtf.format(now) + "\n");
        txtreceipt.setText(txtreceipt.getText() + "Student Number: " + srOfUser.getText() + "\n");
       
        txtreceipt.setText(txtreceipt.getText() + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        txtreceipt.setText(txtreceipt.getText() + "Item   " + "\t" + "Quantity" + "\t" + "Price" + "\n");
        
        for(int i = 0; i < orders.getRowCount(); i++)
        {
            String prodname = (String)orders.getValueAt(i, 0);
            int qty = (int)orders.getValueAt(i, 2);
            int price = (int)orders.getValueAt(i, 3);
            
        txtreceipt.setText(txtreceipt.getText() + prodname + "\t" + qty + "\t" + price + "\n");
        
        }
        txtreceipt.setText(txtreceipt.getText() + "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        txtreceipt.setText(txtreceipt.getText() + "\n");
        
        txtreceipt.setText(txtreceipt.getText()+ "\t" + "\t" + "Total:" + total + "\n");
        txtreceipt.setText(txtreceipt.getText() + "\n");
        txtreceipt.setText(txtreceipt.getText() + "**************************************************************\n");
        txtreceipt.setText(txtreceipt.getText() + "                         This serves as your proof of order.           \n");
        txtreceipt.setText(txtreceipt.getText() + "                                   Thank you.                          \n");
        txtreceipt.setText(txtreceipt.getText() + "**************************************************************\n");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uniform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uniform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uniform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uniform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
    try {
        FlatArcIJTheme.setup();
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uniform().setVisible(true);
            }
        });
    }
    
    private void setIconImage() { // Setting the icon of the program
        URL iconUrl = this.getClass().getResource("images/univ_shop_icon.png");
        Toolkit tk = this.getToolkit();
        setIconImage(tk.getImage(iconUrl));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBtn;
    private javax.swing.JPanel footer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel srOfUser;
    private javax.swing.JPanel subhead;
    private javax.swing.JLabel subheadTime;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextArea txtreceipt;
    private javax.swing.JTextField txttotal;
    private javax.swing.JLabel uniformHeader;
    private javax.swing.JTextField uniformPrice;
    private javax.swing.JTextField uniformText;
    // End of variables declaration//GEN-END:variables
}
